=== alexthaler/marklogic-ant-tasks/sample-build/output/local/_framework/schema/domain.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://www.xquerrail-framework.com/domain"
    xmlns:domain="http://www.xqerrail-framework.com/domain"
    xmlns:builder="http://www.xquerrail-framework.com/builder"
    targetNamespace="http://www.xquerrail-framework.com/domain" elementFormDefault="qualified">

    <xs:element name="domain" type="domainType"/>
    <xs:complexType name="domainType">
        <xs:sequence>
            <xs:sequence>
                <xs:element name="name" type="xs:ID" minOccurs="1" maxOccurs="1"/>
                <xs:element name="content-namespace" type="namespaceDeclarationType" minOccurs="1" maxOccurs="1"/>
                <xs:element name="application-namespace" type="xs:anyURI" minOccurs="0"
                    maxOccurs="1"/>
                <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="author" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="version" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="declare-namespace" type="namespaceDeclarationType" minOccurs="0" maxOccurs="unbounded"/>
                
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                    <xs:element name="model" type="modelType" minOccurs="0" maxOccurs="unbounded"></xs:element>
                    <xs:element name="controller" type="controllerType" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
                <xs:choice minOccurs="0" maxOccurs="unbounded">
                    <xs:element name="hasMany">
                        <xs:complexType>
                            <xs:attributeGroup ref="relationshipAttributes"/>
                        </xs:complexType>
                    </xs:element>
                </xs:choice>
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="constraintType">
        <xs:attributeGroup ref="constraintAttributes"/>
    </xs:complexType>
    
    <xs:complexType name="namespaceDeclarationType">
        <xs:attribute name="prefix"/>
        <xs:attribute name="namespace-uri"/>
    </xs:complexType>

    <xs:complexType name="controllerType">
            <xs:attributeGroup ref="controllerBaseAttributes"> </xs:attributeGroup>
    </xs:complexType>

    <xs:complexType name="modelType">
            <xs:sequence>
                <xs:choice minOccurs="1" maxOccurs="1">
                    <xs:element name="document" type="xs:anyURI" />
                    <xs:element name="directory" type="xs:anyURI"/>
                </xs:choice>
                <xs:element name="declare-namespace" type="namespaceDeclarationType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="default-namespace" type="namespaceDeclarationType" minOccurs="0" maxOccurs="1"/>
                <xs:element name="import-model" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:attributeGroup ref="importModelAttributes"/>
                    </xs:complexType>
                </xs:element>
                <xs:choice minOccurs="1" maxOccurs="unbounded">
                    <xs:element name="element" type="fieldType" minOccurs="0" maxOccurs="unbounded"></xs:element>
                    <xs:element name="attribute" type="fieldType" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="container" type="containerType" minOccurs="0" maxOccurs="unbounded"/>
                    <xs:element name="optionlist" type="optionListType" minOccurs="0" maxOccurs="unbounded"/>
                </xs:choice>
                <xs:element name="hasMany" type="relationType" minOccurs="0" maxOccurs="unbounded"/> 
            </xs:sequence>
            <xs:attributeGroup ref="modelBaseAttributes"/>
    </xs:complexType>
    
    <xs:complexType name="contentModelType">
        <xs:sequence>
            <xs:element name="directory" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="/.*/"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="document" minOccurs="0" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="/.*/"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="fieldType">
        <xs:sequence minOccurs="0" maxOccurs="2">
            <xs:element name="navigation" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attributeGroup ref="navigationAttributes"/>
                </xs:complexType>
            </xs:element> 
            <xs:element name="constraint" minOccurs="0" maxOccurs="1">
              <xs:complexType>
                  <xs:attributeGroup ref="constraintAttributes"/>
              </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attributeGroup ref="fieldAttributes"/>
    </xs:complexType>
    <xs:complexType name="relationType">
        <xs:attributeGroup ref="relationshipAttributes"/>
    </xs:complexType>
    
    <xs:complexType name="containerType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="element" type="fieldType"/>
            <xs:element name="attribute" type="fieldType"/>
        </xs:choice>
    </xs:complexType>
    
    <xs:complexType name="optionListType">
        <xs:sequence>
            <xs:element name="option" type="optionType" minOccurs="1" maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
        <xs:attributeGroup ref="optionListAttributes"></xs:attributeGroup>
    </xs:complexType>
    
    
    <xs:complexType name="optionType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="label" type="xs:string">
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    
    <xs:attributeGroup name="importModelAttributes">
        <xs:attribute name="name" type="xs:Name"/>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="importLibraryGroup">
        <xs:attribute name="name" type="xs:string"/>
        <xs:attribute name="reference" type="xs:string"/>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="optionListAttributes">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="child-element" type="xs:string" />
        <xs:attribute name="type" type="dataType"/>         
    </xs:attributeGroup>
    
    <xs:attributeGroup name="optionAttributes">
        <xs:attribute name="key" type="xs:string"/>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="controllerBaseAttributes">
        <xs:attribute name="name" type="xs:NCName"/>
        <xs:attribute name="model" type="xs:IDREF"/>
        <xs:attribute name="multi" type="xs:boolean"/>
        <xs:attribute name="label" type="xs:string" />
    </xs:attributeGroup>
    
    <xs:attributeGroup name="modelBaseAttributes">
        <xs:attribute name="name" type="xs:ID"/>
        <xs:attribute name="namespace" type="xs:anyURI"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="label" type="xs:string"/>
        <xs:attribute name="persistence">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="document"/>
                    <xs:enumeration value="directory"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>
    
    <xs:attributeGroup name="fieldAttributes">
        <xs:attribute name="name" type="xs:Name"/>
        <xs:attribute name="namespace" type="xs:anyURI"/>
        <xs:attribute name="type" type="dataType"/>
        <xs:attribute name="label" type="xs:string"/>
        <xs:attribute name="description" type="xs:string"/>
        <xs:attribute name="identity" type="xs:boolean"/>
        <xs:attribute name="reference">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\i\c*:\i\c*\:\i\c*"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="default" type="xs:string"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="constraintAttributes">
        <xs:attribute name="inList" type="xs:Name"/>
        <xs:attribute name="required" type="xs:boolean"/>
        <xs:attribute name="minLength" type="xs:integer"/>
        <xs:attribute name="maxLength" type="xs:integer"/>
        <xs:attribute name="unique" type="xs:boolean"/>
        <xs:attribute name="nillable" type="xs:boolean"/>
        <xs:attribute name="minValue" type="xs:string"/>
        <xs:attribute name="maxValue" type="xs:string"/>
        <xs:attribute name="pattern" type="xs:string"/>
        <xs:attribute name="matcher" type="matcherType"/>
        <xs:attribute name="validator">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:pattern value="\i\c*:(model|lib):\i\c*"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:attributeGroup>

    <xs:attributeGroup name="navigationAttributes">
        <xs:attribute name="securable" type="xs:boolean"/>
        <xs:attribute name="searchable" type="xs:boolean"/>
        <xs:attribute name="sortable" type="xs:boolean"/>
        <xs:attribute name="facetable" type="xs:boolean"/>
        <xs:attribute name="newable" type="xs:boolean"/>
        <xs:attribute name="editable" type="xs:boolean"/>
        <xs:attribute name="listable" type="xs:boolean"/>
        <xs:attribute name="removable" type="xs:boolean"/>
        <xs:attribute name="findable" type="xs:boolean"/>
    </xs:attributeGroup>

    <xs:attributeGroup name="relationshipAttributes">
        <xs:attribute name="name" type="xs:Name"/>
        <xs:attribute name="type" type="xs:string"/>
        <xs:attribute name="reference" type="xs:string"/>
        <xs:attribute name="create" type="referenceIntegrity"/>
        <xs:attribute name="read" type="referenceIntegrity"/>
        <xs:attribute name="update" type="referenceIntegrity"/>
        <xs:attribute name="delete" type="referenceIntegrity"/>
    </xs:attributeGroup>


    <xs:simpleType name="dataType">
        <xs:restriction base="xs:string">
            <!--Generic Types-->
            <xs:enumeration value="string"/>
            <xs:enumeration value="integer"/>
            <xs:enumeration value="long"/>
            <xs:enumeration value="decimal"/>
            <xs:enumeration value="double"/>
            <xs:enumeration value="float"/>
            <xs:enumeration value="boolean"/>
            <xs:enumeration value="anyURI"/>
            <xs:enumeration value="date"/>
            <xs:enumeration value="dateTime"/>
            <xs:enumeration value="time"/>
            <xs:enumeration value="duration"/>
            <xs:enumeration value="dayTime"/>
            <xs:enumeration value="yearMonth"/>
            <xs:enumeration value="monthDay"/>
            <xs:enumeration value="binary"/>
            <!--Model Custom-->
            <xs:enumeration value="identity"/>
            <xs:enumeration value="reference"/>
            <xs:enumeration value="update-timestamp"/>
            <xs:enumeration value="update-user"/>
            <xs:enumeration value="create-timestamp"/>
            <xs:enumeration value="create-user"/>
            <xs:enumeration value="attachment"/>
            <xs:enumeration value="schema-element"/>
            <xs:enumeration value="query"/>
            <xs:enumeration value="point"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="matcherType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="email"/>
            <xs:enumeration value="url"/>
            <xs:enumeration value="ssn"/>
            <xs:enumeration value="uuid"/>
            <xs:enumeration value="creditCard"/>
            <xs:enumeration value="custom"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="referenceIntegrity">
        <xs:restriction base="xs:string">
            <xs:enumeration value="cascade"/>
            <xs:enumeration value="notify"/>
            <xs:enumeration value="none"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="identityType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="guid"/>
            <xs:enumeration value="random"/>
            <xs:enumeration value="timestamp"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== alexthaler/marklogic-ant-tasks/sample-build/output/modules/application/domain/condenast-domain.xml
<domain xmlns="http://www.xquerrail-framework.com/domain"
    xmlns:security="http://www.xquery/security"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.xquerrail-framework.com/domain file:../../_framework/schema/domain.xsd">
    <name>application</name>
    <content-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
    <application-namespace>http://www.condenast.com/dam/2.0</application-namespace>
    <description>Conde Nast DAM 2.0</description>
    <author>Andrew Wanczowski, Gary Vidal</author>
    <version>1.0</version>

    <declare-namespace prefix="dcterms" namespace-uri="http://purl.org/dc/terms/"/>
    <declare-namespace prefix="cnp" namespace-uri="reserved path"/>
    
    <!--
    <roles>
        <role name="cndam-admin" type="admin"/>
        <role name="cndam-editor" type="editor"/>
        <role name="cndam-user" type="user"/>
        <role name="cndam-nobody" type="anonymous"/>
        <role name="cndam-create" type="create"/>
        <role name="cndam-read" type="read"/>
        <role name="cndam-write" type="write"/>
        <role name="cndam-delete" type="delete"/>
        <role name="cndam-execute" type="execute"/>
    </roles>
    -->
    
    <!-- Georgraphic Related Models -->
    <model name="countryCode" description="Country Code Controlled Vocabulary" persistence="document">
        <document>/vocabularies/countryCodes.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <element name="id" type="string" identity="true" label="ISO Country Code">
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="name" type="string" label="Name">
            <navigation searchable="true" sortable="true" />
            <constraint  required="true"/>
        </element>
        <element name="iso3" type="integer" label="ISO 3 digit">
            <navigation searchable="true" sortable="true" />
            <constraint  required="true"/>
        </element>
    </model>
    <model name="timezone" description="Timezones Configuration" persistence="document">
        <document>/vocabularies/timezones.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <element name="id" type="string" identity="true" label="ID">
            <navigation searchable="true" sortable="true" facetable="true" />
            <constraint required="true"/>
        </element>
        <element name="offset" type="decimal" label="GMT Offset">
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="name" type="string" label="Name">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
    </model>
    <model name="locale" description="Locales" persistence="document">
        <document>/vocabularies/locales.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <element name="id" type="string" identity="true" >
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="name" type="string">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
    </model>

    <!-- Publication Related Models -->
    <model name="publicationGroup" description="Publication Group" persistence="document">
        <document>/authorities/publicationGroups.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <element name="id" type="string" identity="true" >
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="name" type="string">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
    </model>
    <model name="publication" description="Publication Group" persistence="document">
        <document>/vocabularies/publications.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/> 
        <import-model name="issnCode"/>
        <element name="publicationId" type="string" identity="true" label="ID">
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="publicationName" type="string" label="Publication Name">
            <navigation searchable="true" sortable="true"/>
            <constraint required="true"/>
        </element>
        <element name="issnNumber" type="string" label="ISSN Number">
            <navigation searchable="true" sortable="true"/>
            <constraint required="true"/>
        </element>
        <hasMany name="issnCodes" type="issnCode" reference="model:issnCode:reference"/>        
    </model>
    <model name="issnCode" description="ISSN Codes" persistence="document">
        <document>/vocabularies/issnCodes.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <element name="id" type="string" identity="true">
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="name" type="string">
            <navigation searchable="true" sortable="true"/>
            <constraint required="true"/>
        </element>
    </model>
    
    <!-- Ingestion Related Models -->
    <model name="packageType" description="Package Type" persistence="document">
        <document>/packageTypes/packageTypes.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <import-model name="assetType"/>
        <element name="id" type="string" identity="true" >
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="name" type="string">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
       	<hasMany name="assetTypes" type="assetType" reference="model:assetType:reference"/>
    </model>    
    <model name="assetType" description="AssetType" persistence="document">
        <document>/assetTypes/assetTypes.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <element name="id" type="string" identity="true" label="ID" >
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="description" type="string" label="Asset Description">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
        <element name="namespace-uri" type="string" label="Namespace">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
        <element name="element" type="string" label="Root Name">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
        <element name="xmlSchemaLocation" type="string" label="Schema Location">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
        <element name="isActive" type="boolean" label="Active">
            <navigation searchable="true" sortable="true"/>
            <constraint  required="true"/>
        </element>
    </model>  

    <!-- Start Validation Models -->
    <model name="schema" description="Schemas for validating ingested content" persistence="document">
        <document>/config/validation/schemas.xml</document>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <element name="id" type="string" identity="true" label="Schema ID">
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="name" type="string" label="Name">
            <navigation searchable="true" sortable="true" />
            <constraint  required="true"/>
        </element>
        <element name="schemaLocation" type="string" label="Schema Location">
            <navigation searchable="true" sortable="true" />
            <constraint  required="true"/>
        </element>
        <element name="namespace" type="string" label="Schema namespace">
            <navigation searchable="true" sortable="true" />
            <constraint  required="true"/>
        </element>
        <element name="isPrimary" type="boolean" label="Is Primary Schema">
            <navigation searchable="true" sortable="true" />
            <constraint  required="true"/>
        </element>
    </model>
    <model name="schematron" description="Schematron for validating ingested content" persistence="directory">
        <directory>/schematrons/</directory>
        <declare-namespace prefix="cndam" namespace-uri="http://www.condenast.com/dam/2.0"/>
        <element name="id" type="string" identity="true" label="Schematron ID">
            <navigation searchable="true" sortable="true" facetable="true"/>
            <constraint required="true"/>
        </element>
        <element name="name" type="string" label="Name">
            <navigation searchable="true" sortable="true" />
            <constraint required="true"/>
